version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: cp_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: cp_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/crosspromo_assets
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: cp_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
